stages:
- build
- test
- deploy

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - Source/magiccam/.gradle/

build:apk:
  image: jangrewe/gitlab-ci-android
  stage: build
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/Source/magiccam/.gradle
    - chmod +x ./Source/magiccam/gradlew
  script:
  - cd Source/magiccam
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - Source/magiccam/app/build/outputs/
  only:
    changes:
      - Source/magiccam/*

test:web:
  stage: test
  before_script:
    - export FLASK_SERVER_DIR=$(pwd)/Source/flask-server
    - cd $FLASK_SERVER_DIR
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - pytest
  only:
    changes:
      - Source/flask-server/*.py

deploy:web:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=magiccam --api-key=$HEROKU_API_KEY
  only:
    changes:
      - Source/flask-server/*