stages:
- build
- test
- deploy

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - Source/magiccam/.gradle/

build:apk:
  image: jangrewe/gitlab-ci-android
  stage: build
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/Source/magiccam/.gradle
    - chmod +x ./Source/magiccam/gradlew
  script:
  - cd Source/magiccam
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - Source/magiccam/app/build/outputs/
  rules:
    - changes:
      - Source/magiccam/*

test:web:
  image: python:3.7.7-slim
  stage: test
  before_script:
    - export FLASK_SERVER_DIR=$(pwd)/Source/flask-server
    - cd $FLASK_SERVER_DIR
  script:
    - pip install -r requirements.txt
    - pytest
  rules:
    - changes:
      - Source/flask-server/*

deploy:web:
  stage: deploy
  before_script:
    - export FLASK_SERVER_DIR=$(pwd)/Source/flask-server
    - cd $FLASK_SERVER_DIR
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=magiccam --api-key=$HEROKU_API_KEY
  rules:
    - changes:
      - Source/flask-server/*